// The demonstration on the landing page.
//
// A marketing page making a claim about what the product says is a claim
// that can drift from what the product says. This one cannot, because it is
// generated by the product — and these tests are what keep that true rather
// than merely intended.

import { describe, expect, it } from "vitest";
import { NOTICING_CAPTION, florence, whatItNoticed } from "@/lib/marketing/noticing";
import { noticeThisWeek } from "@/lib/graph/notice";

describe("what the landing page shows", () => {
  it("finds three things worth saying", () => {
    expect(whatItNoticed("2026-08-08")).toHaveLength(3);
  });

  it("shows a different kind of observation each time", () => {
    // Three surge lines would demonstrate counting. One thing that stopped,
    // one that came back and one that is everywhere demonstrates noticing,
    // which is the claim being made.
    const shapes = whatItNoticed("2026-08-08").map((o) => o.shape);
    expect(new Set(shapes).size).toBe(3);
    expect(shapes).toContain("faded");
  });

  it("moves with the calendar rather than naming a fixed month", () => {
    // The failure this prevents is invisible: a hard-coded "since April" is
    // correct in April and wrong for the other eleven months, and the page
    // still looks perfectly fine while being wrong.
    const winter = whatItNoticed("2026-08-08").find((o) => o.shape === "faded")!;
    const summer = whatItNoticed("2026-02-08").find((o) => o.shape === "faded")!;
    expect(winter.line).not.toBe(summer.line);
    expect(winter.line).toMatch(/last appeared in \w+\.$/);
  });

  it("is the engine's output, not a copywriter's", () => {
    // Re-derived rather than described: the page's lines must be exactly
    // what noticeThisWeek() returns for the fixture. Replace the module with
    // three well-chosen sentences and this fails, which is the whole reason
    // the section is allowed to make the claim it makes.
    const today = "2026-08-08";
    expect(whatItNoticed(today)).toEqual(
      noticeThisWeek({ today, entities: florence(today) })
    );
  });

  it("can trace every line back to the memories it was counted from", () => {
    // The provenance rule. The page prints "counted from n memories" under
    // each line, and that number has to be real.
    for (const o of whatItNoticed("2026-08-08")) {
      expect(o.memoryIds.length).toBeGreaterThanOrEqual(2);
      expect(new Set(o.memoryIds).size).toBe(o.memoryIds.length);
    }
  });

  it("counts and never interprets, on the marketing page too", () => {
    // The rule is easiest to break here, where the temptation to write
    // something moving is strongest.
    for (const o of whatItNoticed("2026-08-08")) {
      expect(o.line).not.toMatch(
        /loves|favourite|happy|sad|enjoys|misses|obsessed|clearly|must have|adorable/i
      );
    }
  });

  it("says out loud that the family is invented", () => {
    // Non-negotiable. A page implying these were a real child's memories
    // would be doing the exact thing the product promises never to do.
    expect(NOTICING_CAPTION).toMatch(/made-up|invented|fiction/i);
    expect(NOTICING_CAPTION).toMatch(/Florence/);
  });
});
