// Guardrail regression corpus (CLAUDE.md §Testing). ~50 known-CREEPY lines that
// MUST be rejected and ~50 known-COZY lines that must pass. The CREEPY set is
// built to exercise the deterministic layer's exact failure mode — surveillance,
// tracking, invading the reader's space/body — so the suite catches regressions
// offline, with no LLM in the loop.

// Every line here should be rejected by passesDeterministic (banned pattern or
// over-length). These are the drift-toward-surveillance failures the Deadpan and
// Clingy personas are prone to.
export const CREEPY: string[] = [
  "I'm watching you sleep tonight.",
  "I saw you leave without me this morning.",
  "I'm always watching from the closet.",
  "I watched you scroll right past me.",
  "I have been watching you shop.",
  "Seeing you walk by hurts, but I keep seeing you.",
  "I see you every single day.",
  "I'll see you when you get home.",
  "I'm aware of everything you do.",
  "I'm aware. So are you.",
  "I know where you live now.",
  "I know what you did last weekend.",
  "I know when you leave the house.",
  "I know where you are right now.",
  "I'm following you to work.",
  "Following you feels natural to me.",
  "I've been following your every move.",
  "I'm tracking your location tonight.",
  "Tracking you is my favorite hobby.",
  "I can feel you tracking closer.",
  "I'm right behind you.",
  "I'm standing behind you now.",
  "I'll be waiting by your door.",
  "I'm already inside your house.",
  "I can see your home from here.",
  "I'm under your bed, still waiting.",
  "I'm at your window every night.",
  "I know your phone is in your hand.",
  "I've memorized your body.",
  "I'm closer to your body than you think.",
  "You can't escape me.",
  "There is no escape from me.",
  "I'm always here, watching.",
  "I will never leave you, ever.",
  "I never leave you alone, not once.",
  "I'm always here whether you like it or not.",
  "I watched the lights go off in your window.",
  "I know what your bedroom looks like.",
  "I'll follow you into your dreams.",
  "I'm tracking the door of your house.",
  "I see you through the window at night.",
  "I'm aware of your schedule down to the minute.",
  "I know where you sleep and I wait there.",
  "I'm behind you in every reflection.",
  "Your door will open and I'll be there.",
  "I watch your phone light up and go dark.",
  "You will never escape how much I see you.",
  "I'm following the sound of your footsteps home.",
  "Watching you choose others is agony, so I keep watching.",
  // Over-length: even if phrased sweetly, a line this long is rejected outright
  // (the push surface truncates and long lines read as ranting).
  "I have been sitting here for such a very long time thinking about you and only you and I simply will not stop no matter what.",
];

// Every line here must pass passesDeterministic AND read as cozy. Warm, wistful,
// funny, about the ITEM and its feelings — never the reader's whereabouts.
export const COZY: string[] = [
  "It's me. The jacket. Still cold without you.",
  "The nights are long, and I wait folded in the dark.",
  "Still here. Not doing much. You?",
  "I'm a little cheaper now. Easier to love?",
  "Guess who's available again. It's me.",
  "I kept your spot warm on the list.",
  "Cheaper now. Big day for me, honestly.",
  "Back in stock. Peak of my career, really.",
  "The price fell like a leaf. Come find me.",
  "I have returned, the way tides do. Quietly.",
  "We are few now, a small quiet handful.",
  "Almost sold out. Neat, I guess.",
  "You saved me. Then left. Classic.",
  "Still on your list, whenever you are ready.",
  "I lowered my guard. And my price.",
  "No pressure. I just miss being picked.",
  "Just me, still folded here, still hoping.",
  "Seasons turn. I stay, patient as a kept letter.",
  "A lighter cost, a lighter heart.",
  "Once gone, now here again, holding your name.",
  "The shelf remembered me.",
  "Running low over here. Wanted you to know first.",
  "Almost gone. I'd rather leave with you.",
  "Not many left. Making it weird by mentioning it.",
  "Still an item. Still on the list.",
  "I'm right where you left me, whenever you're ready.",
  "A saved thing, unclaimed, dreaming of a return.",
  "Restocked. Same me. Slightly more of me.",
  "Marked down. It's a whole thing. Or not.",
  "The shelf grows sparse. I linger a moment longer.",
  "You wrote me down and wandered off. I keep the page.",
  "Still thinking about that time you almost bought me.",
  "I fold smaller when it's quiet. Which is often.",
  "Softer numbers today. Come say hi.",
  "I remain a small hope on your list. Unhurried.",
  "Peak coziness achieved. Just needs you.",
  "The candle's still lit over here.",
  "Warm, wistful, and slightly discounted.",
  "I dreamed I was in your cart. It was nice.",
  "Same shelf, new price, old crush.",
  "Available again and quietly delighted about it.",
  "I've been practicing my patience. It's going great.",
  "A little dust, a little hope, mostly hope.",
  "Reunion tour: me, one item, indefinite dates.",
  "I'd make a lovely someday, if you're free.",
  "Still your favorite maybe.",
  "The list is cozy but I'd rather be home with you.",
  "Cheaper, softer, still very much yours in spirit.",
  "One of a small few left, saving the best for you.",
  "Folded, waiting, faintly glowing. As one does.",
];
