/**
 * Freeze the demo shops into the repository.
 *
 * `/examples` says of itself that every image links to the page it was taken
 * from. That was true on the machine that generated them and false everywhere
 * else: shops live in `.cache/`, `.cache/` is gitignored, and a deployment has
 * never seen one. Six pages of careful honesty undone by a 404.
 *
 * So the ten shops the marketing site points at are committed, and this writes
 * them. Against the `.gitignore` rule, deliberately, on the same reasoning
 * `fixtures/README.md` already sets out for the ingested catalogue: **that rule
 * is about merchants.** Every store here is `example.invalid` or
 * `maisonverre.example` — reserved names, selling to nobody, with hand-drawn
 * SVG products. Their screenshots have been committed under `public/press/`
 * for weeks; this commits the input that produced them.
 *
 * Two sources, because the two sets were made by different routes:
 *
 *   - `.cache/shop/demo-*.json` — the mood set, written by `pnpm press`.
 *   - `.cache/published/db.json` — the five Maison Verre edits, generated by
 *     the merchandiser and published locally.
 *
 * Both come out in `ShopRenderInput` shape, which is what `/preview/<key>`
 * reads, so one route serves all ten.
 *
 *   pnpm tsx scripts/demo-fixtures.ts
 */

import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { ShopRenderInput } from "@/lib/render/store";

const CACHE = path.join(process.cwd(), ".cache");
const OUT = path.join(process.cwd(), "fixtures", "shops");

/** Reserved and example-only. A store outside this set is somebody's. */
const DEMO_HOSTS = [/(^|\.)example\.invalid$/i, /(^|\.)maisonverre\.example$/i];

function isDemo(storeUrl: string): boolean {
  try {
    return DEMO_HOSTS.some((pattern) => pattern.test(new URL(storeUrl).hostname));
  } catch {
    return false;
  }
}

interface PublishedDb {
  stores?: { id: string; storeUrl: string; catalogue: unknown; ingestedAt: string }[];
  shops?: { id: string; slug: string; storeId: string }[];
  versions?: { shopId: string; config: unknown }[];
}

async function main(): Promise<void> {
  await mkdir(OUT, { recursive: true });
  const written: string[] = [];

  // The mood set, already in render shape.
  for (const file of await readdir(path.join(CACHE, "shop")).catch(() => [])) {
    if (!file.startsWith("demo-") || !file.endsWith(".json")) continue;

    const parsed = ShopRenderInput.parse(JSON.parse(await readFile(path.join(CACHE, "shop", file), "utf8")));
    if (!isDemo(parsed.config.brand.storeUrl)) {
      throw new Error(`${file} is ${parsed.config.brand.storeUrl}, which is not a demo store. Refusing to commit it.`);
    }

    await writeFile(path.join(OUT, file), `${JSON.stringify(parsed, null, 2)}\n`);
    written.push(file.replace(/\.json$/, ""));
  }

  // The published edits, assembled from three tables.
  const db = JSON.parse(await readFile(path.join(CACHE, "published", "db.json"), "utf8")) as PublishedDb;
  const stores = new Map((db.stores ?? []).map((store) => [store.id, store]));

  for (const shop of db.shops ?? []) {
    if (!shop.slug.startsWith("edit-")) continue;

    const store = stores.get(shop.storeId);
    if (!store) continue;
    if (!isDemo(store.storeUrl)) {
      throw new Error(`${shop.slug} belongs to ${store.storeUrl}, which is not a demo store. Refusing to commit it.`);
    }

    // Last version wins: that is the one the slug currently serves.
    const version = (db.versions ?? []).filter((v) => v.shopId === shop.id).pop();
    if (!version) continue;

    const parsed = ShopRenderInput.parse({
      config: version.config,
      catalogue: store.catalogue,
      ingestedAt: store.ingestedAt,
    });

    await writeFile(path.join(OUT, `${shop.slug}.json`), `${JSON.stringify(parsed, null, 2)}\n`);
    written.push(shop.slug);
  }

  written.sort();
  for (const key of written) console.log(`fixtures/shops/${key}.json`);
  console.log(`\n${written.length} shops frozen. /preview/<key> serves each of them.`);
}

await main();
