/**
 * Freeze the demo shops into the repository.
 *
 * `/examples` says of itself that every image links to the page it was taken
 * from. That was true on the machine that generated them and false everywhere
 * else: shops live in `.cache/`, `.cache/` is gitignored, and a deployment has
 * never seen one. Six pages of careful honesty undone by a 404.
 *
 * So the ten shops the marketing site points at are committed, and this writes
 * them. Against the `.gitignore` rule, deliberately, on the same reasoning
 * `fixtures/README.md` already sets out for the ingested catalogue: **that rule
 * is about merchants.** Every store here is `example.invalid` or
 * `maisonverre.example` — reserved names, selling to nobody, with hand-drawn
 * SVG products. Their screenshots have been committed under `public/press/`
 * for weeks; this commits the input that produced them.
 *
 * Two sources, because the two sets were made by different routes:
 *
 *   - `.cache/shop/demo-*.json` — the mood set, written by `pnpm press`.
 *   - `.cache/published/db.json` — the five Maison Verre edits, generated by
 *     the merchandiser and published locally.
 *
 * Both come out in `ShopRenderInput` shape, which is what `/preview/<key>`
 * reads, so one route serves all ten.
 *
 *   pnpm tsx scripts/demo-fixtures.ts
 */

import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { ShopRenderInput } from "@/lib/render/store";

const CACHE = path.join(process.cwd(), ".cache");
const OUT = path.join(process.cwd(), "fixtures", "shops");

/** Reserved and example-only. A store outside this set is somebody's. */
const DEMO_HOSTS = [/(^|\.)example\.invalid$/i, /(^|\.)maisonverre\.example$/i, /(^|\.)casalino\.example$/i];

function isDemo(storeUrl: string): boolean {
  try {
    return DEMO_HOSTS.some((pattern) => pattern.test(new URL(storeUrl).hostname));
  } catch {
    return false;
  }
}

async function main(): Promise<void> {
  await mkdir(OUT, { recursive: true });
  const written: string[] = [];

  /*
   * Everything already in render shape.
   *
   * This used to take `demo-*` from here and the five `edit-*` from
   * `.cache/published/db.json`, which was right when the edits only existed as
   * published shops. `pnpm press:edits` now writes them here through
   * `saveShop`, so the published table is the stale copy — and freezing from it
   * silently overwrote a fresh generation with an older one, leaving the
   * committed screenshots and the committed fixtures describing different
   * shops. The published branch below is kept as a fallback for anything not
   * found here.
   */
  for (const file of await readdir(path.join(CACHE, "shop")).catch(() => [])) {
    if (!/^(demo|edit)-/.test(file) || !file.endsWith(".json")) continue;

    const parsed = ShopRenderInput.parse(JSON.parse(await readFile(path.join(CACHE, "shop", file), "utf8")));
    if (!isDemo(parsed.config.brand.storeUrl)) {
      throw new Error(`${file} is ${parsed.config.brand.storeUrl}, which is not a demo store. Refusing to commit it.`);
    }

    await writeFile(path.join(OUT, file), `${JSON.stringify(parsed, null, 2)}\n`);
    written.push(file.replace(/\.json$/, ""));
  }

  /*
   * The published-database fallback is gone, and its absence is the fix.
   *
   * It existed for when the five edits lived only as published shops.
   * `pnpm press:edits` writes them through `saveShop` now, so the published
   * table was already the stale copy — and it did worse than sit there. Moving
   * the demo brand from glassware to linen renamed three of the five slugs, and
   * this branch put `edit-bar`, `edit-first` and `edit-gift` straight back into
   * `fixtures/` from a run weeks old. Three dead shops, in the repository,
   * linked from nowhere, describing a catalogue the site no longer sells.
   *
   * A fallback that can only ever be more stale than the thing it backs up is
   * not a safety net.
   */

  written.sort();
  for (const key of written) console.log(`fixtures/shops/${key}.json`);
  console.log(`\n${written.length} shops frozen. /preview/<key> serves each of them.`);
}

await main();
