#!/usr/bin/env tsx
/**
 * The five shops on the front page, rebuilt from the demo catalogue.
 *
 * `pnpm press` regenerates the five *mood* shops — one brand each, five
 * templates — and captures them as `shop-<mood>.jpg`. It does not touch the
 * five on the front page under "One catalogue. Five shops.", which are a
 * different and stronger claim: one catalogue, five sentences, five different
 * selections. Those live as `edit-*` and were generated by hand.
 *
 * That gap made a promise false. `public/demo/README.md` says photographs
 * dropped into `public/demo/` flow through to the site with one command, and
 * until now that was only true of the hero. The main proof section would have
 * kept its drawings, which is the one place it matters most.
 *
 * So this closes the chain:
 *
 *   demo catalogue → ingest fixture → five merchandiser calls → five shops
 *
 * Run it after `pnpm press` has rebuilt the catalogues, then capture:
 *
 *   pnpm press
 *   pnpm press:edits
 *   pnpm press:capture-edits
 *
 * It calls the real merchandiser, so it needs `POPUUP_ANTHROPIC_API_KEY` and
 * `AI_PROVIDER=anthropic`. Without them the deterministic default assembles
 * something defensible and identical five times over, which would quietly
 * destroy the only thing this section is arguing.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { merchandise } from "../../src/lib/merchandise/index";
import { saveShop } from "../../src/lib/render/store";
import { hasAnthropicKey, MISSING_KEY } from "../../src/lib/anthropic-key";
import { BrandContext, IngestResult } from "../../src/lib/ingest/types";

/**
 * The five sentences, and the slugs they publish to.
 *
 * These are the page's own copy — `EDITS` in `src/app/page.tsx` quotes each
 * prompt verbatim beside the shop it produced. Changing one here without
 * changing it there would put a sentence next to a shop it never made, which
 * is the exact dishonesty the section exists to disprove.
 */
const EDITS = [
  { slug: "edit-ibiza", prompt: "the Ibiza edit — swim first, linen next, nothing over 180" },
  { slug: "edit-escape", prompt: "for someone going somewhere hot in February" },
  { slug: "edit-wedding", prompt: "for a wedding abroad, and I am a guest" },
  { slug: "edit-budget", prompt: "everything under 80" },
  { slug: "edit-sale", prompt: "what is left, cheapest first" },
];

const CACHE = path.join(process.cwd(), ".cache");
/** The demo store. Reserved by RFC 2606, so it can never be a real merchant. */
const STORE = "https://casalino.example";
const INGEST = path.join(CACHE, "ingest", "casalino.example.json");
const SOURCE = path.join(CACHE, "shop", "demo-editorial.json");

/**
 * Rebuild the ingest fixture from the demo catalogue.
 *
 * This is the step that carries the photographs. `scripts/press/shops.mjs`
 * writes `demo-editorial.json` with whatever is in `public/demo/casa-lino/`, and
 * this copies that catalogue into the shape the merchandiser reads. Skip it
 * and the five shops keep whatever imagery they were built with, however long
 * ago.
 */
async function refreshIngest(): Promise<IngestResult> {
  const demo = JSON.parse(await readFile(SOURCE, "utf8")) as {
    catalogue: IngestResult["catalogue"];
    config: {
      brand: { name: string; tagline?: string; storeUrl: string };
      theme: { colorway: BrandContext["suggestedColorway"] };
    };
  };

  let existing: IngestResult | null = null;
  try {
    existing = JSON.parse(await readFile(INGEST, "utf8")) as IngestResult;
  } catch {
    // First run. Everything below is rebuilt from the demo anyway.
  }

  /*
   * The fallback brand, built to the type rather than to a guess.
   *
   * This branch had never actually run. It wrote `voice: null`, `logo: null`
   * and a `tagline` of `null`, none of which `BrandContext` permits — and it
   * went unnoticed for as long as a fixture existed on disk from a previous
   * run, because the `existing?.brand ?? …` above kept choosing the file.
   * Pointing the pipeline at a new demo brand deleted that cover and the
   * merchandiser died dereferencing `brand.voice.headings`.
   *
   * So it is parsed through the schema now. A fallback that is only exercised
   * on a first run is exactly the code that should be checked by something
   * other than being run.
   */
  const ingestedAt = new Date().toISOString();
  const brand: BrandContext =
    existing?.brand ??
    BrandContext.parse({
      name: demo.config.brand.name,
      storeUrl: STORE,
      tagline: demo.config.brand.tagline,
      /*
       * Deliberately empty: the merchandiser must not drift a brand's colour
       * per audience, and an empty palette is the honest input for a demo
       * store with no homepage to read one from. `suggestedColorway` carries
       * the brand's actual colours instead, so all five edits come out in the
       * same one — which is the claim the section on the front page makes.
       */
      palette: [],
      suggestedColorway: demo.config.theme.colorway,
      /*
       * No voice evidence, stated as four empty lists rather than as null.
       * There is no homepage to read headings off; the prompt builder handles
       * an empty section and does not handle a missing one.
       */
      voice: { headings: [], sentences: [], navLabels: [], buttonLabels: [] },
      links: [],
      socialLinks: [],
    });

  /*
   * Parsed, not cast.
   *
   * `as IngestResult` was doing the damage. It told the compiler this object
   * was a complete ingest while it was in fact `{...existing}` plus three
   * fields — so every part the spread was silently supplying went unchecked,
   * and pointing the pipeline at a brand with no fixture on disk produced a
   * crash per missing field, one run at a time: first `brand.voice`, then
   * `reviews.note`, with `diagnostics` waiting behind it.
   *
   * Parsing states the whole thing once and fails on the first run with every
   * problem named, rather than on the fifth with the last of them.
   */
  const result = IngestResult.parse({
    store: {
      inputUrl: STORE,
      storeUrl: STORE,
      platform: "shopify",
      catalogueSource: "products.json",
      ingestedAt,
    },
    brand,
    catalogue: demo.catalogue,
    /*
     * Not ingestable, and said so rather than omitted. The brief is explicit:
     * a reviews block built from a store whose reviews were never read would
     * be a page claiming social proof nobody has. A demo store has no review
     * platform to detect, so the answer is a flat no.
     */
    reviews: existing?.reviews ?? {
      available: false,
      platformDetected: null,
      note: "This is a demo catalogue with no storefront behind it, so no reviews were read.",
    },
    diagnostics: existing?.diagnostics ?? {
      warnings: [],
      trace: [{ step: "demo-catalogue", outcome: "ok", detail: "Assembled by scripts/press/shops.mjs, not fetched." }],
    },
  });

  await mkdir(path.dirname(INGEST), { recursive: true });
  await writeFile(INGEST, `${JSON.stringify(result, null, 2)}\n`);
  return result;
}

async function main(): Promise<void> {
  if (!hasAnthropicKey()) {
    process.stderr.write(`\n  ${MISSING_KEY}\n\n`);
    process.exit(1);
  }
  if (process.env.AI_PROVIDER !== "anthropic") {
    process.stderr.write(
      "\n  AI_PROVIDER is not 'anthropic'. The deterministic default would return five\n" +
        "  near-identical shops, which is the opposite of what this section claims.\n\n",
    );
    process.exit(1);
  }

  const ingest = await refreshIngest();
  const photos = ingest.catalogue.products.filter((p) => !p.images[0]?.url.startsWith("data:")).length;
  process.stdout.write(
    `\n  ${ingest.catalogue.products.length} products, ${photos} with photographs, ` +
      `${ingest.catalogue.products.length - photos} still drawn.\n\n`,
  );

  for (const edit of EDITS) {
    const { config } = await merchandise(ingest, edit.prompt);
    await saveShop(edit.slug, {
      config,
      catalogue: ingest.catalogue,
      ingestedAt: ingest.store.ingestedAt,
    });

    const chosen = config.blocks
      .flatMap((b) => ("products" in b.block ? (b.block.products as { handle: string }[]) : []))
      .length;
    process.stdout.write(
      `  ${edit.slug.padEnd(14)} ${String(chosen).padStart(2)} products  ${config.theme.mood.padEnd(10)} ${config.theme.colorway.accent}\n`,
    );
  }

  process.stdout.write(
    "\n  Written to .cache/shop/. Capture them with `pnpm press:capture-edits`,\n" +
      "  then freeze with `pnpm tsx scripts/demo-fixtures.ts`.\n\n",
  );
}

await main();
