#!/usr/bin/env tsx
/**
 * The five shops on the front page, rebuilt from the demo catalogue.
 *
 * `pnpm press` regenerates the five *mood* shops — one brand each, five
 * templates — and captures them as `shop-<mood>.jpg`. It does not touch the
 * five on the front page under "One catalogue. Five shops.", which are a
 * different and stronger claim: one catalogue, five sentences, five different
 * selections. Those live as `edit-*` and were generated by hand.
 *
 * That gap made a promise false. `public/demo/README.md` says photographs
 * dropped into `public/demo/` flow through to the site with one command, and
 * until now that was only true of the hero. The main proof section would have
 * kept its drawings, which is the one place it matters most.
 *
 * So this closes the chain:
 *
 *   demo catalogue → ingest fixture → five merchandiser calls → five shops
 *
 * Run it after `pnpm press` has rebuilt the catalogues, then capture:
 *
 *   pnpm press
 *   pnpm press:edits
 *   pnpm press:capture-edits
 *
 * It calls the real merchandiser, so it needs `POPUUP_ANTHROPIC_API_KEY` and
 * `AI_PROVIDER=anthropic`. Without them the deterministic default assembles
 * something defensible and identical five times over, which would quietly
 * destroy the only thing this section is arguing.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { merchandise } from "../../src/lib/merchandise/index";
import { saveShop } from "../../src/lib/render/store";
import { hasAnthropicKey, MISSING_KEY } from "../../src/lib/anthropic-key";
import type { IngestResult } from "../../src/lib/ingest/types";

/**
 * The five sentences, and the slugs they publish to.
 *
 * These are the page's own copy — `EDITS` in `src/app/page.tsx` quotes each
 * prompt verbatim beside the shop it produced. Changing one here without
 * changing it there would put a sentence next to a shop it never made, which
 * is the exact dishonesty the section exists to disprove.
 */
const EDITS = [
  { slug: "edit-wedding", prompt: "a wedding list for two people who already own everything" },
  { slug: "edit-first", prompt: "for someone moving into their own place, nothing over 60" },
  { slug: "edit-bar", prompt: "for someone who has started making cocktails at home" },
  { slug: "edit-gift", prompt: "for a host who has everything, under 80" },
  { slug: "edit-sale", prompt: "what is left, cheapest first" },
];

const CACHE = path.join(process.cwd(), ".cache");
const INGEST = path.join(CACHE, "ingest", "maisonverre.example.json");
const SOURCE = path.join(CACHE, "shop", "demo-luxe.json");

/**
 * Rebuild the ingest fixture from the demo catalogue.
 *
 * This is the step that carries the photographs. `scripts/press/shops.mjs`
 * writes `demo-luxe.json` with whatever is in `public/demo/maison-verre/`, and
 * this copies that catalogue into the shape the merchandiser reads. Skip it
 * and the five shops keep whatever imagery they were built with, however long
 * ago.
 */
async function refreshIngest(): Promise<IngestResult> {
  const demo = JSON.parse(await readFile(SOURCE, "utf8")) as {
    catalogue: IngestResult["catalogue"];
    config: { brand: { name: string; tagline?: string; storeUrl: string } };
  };

  let existing: IngestResult | null = null;
  try {
    existing = JSON.parse(await readFile(INGEST, "utf8")) as IngestResult;
  } catch {
    // First run. Everything below is rebuilt from the demo anyway.
  }

  const ingestedAt = new Date().toISOString();
  const result: IngestResult = {
    ...(existing ?? ({} as IngestResult)),
    store: {
      inputUrl: "https://maisonverre.example",
      storeUrl: "https://maisonverre.example",
      platform: "shopify",
      catalogueSource: "products.json",
      ingestedAt,
    },
    brand: existing?.brand ?? {
      name: demo.config.brand.name,
      tagline: demo.config.brand.tagline ?? null,
      // Deliberately empty: the merchandiser must not drift the brand's colour
      // per audience, and an empty palette is the honest input for a demo
      // store that has no homepage to read one from.
      palette: [],
      voice: null,
      logo: null,
    },
    catalogue: demo.catalogue,
  } as IngestResult;

  await mkdir(path.dirname(INGEST), { recursive: true });
  await writeFile(INGEST, `${JSON.stringify(result, null, 2)}\n`);
  return result;
}

async function main(): Promise<void> {
  if (!hasAnthropicKey()) {
    process.stderr.write(`\n  ${MISSING_KEY}\n\n`);
    process.exit(1);
  }
  if (process.env.AI_PROVIDER !== "anthropic") {
    process.stderr.write(
      "\n  AI_PROVIDER is not 'anthropic'. The deterministic default would return five\n" +
        "  near-identical shops, which is the opposite of what this section claims.\n\n",
    );
    process.exit(1);
  }

  const ingest = await refreshIngest();
  const photos = ingest.catalogue.products.filter((p) => !p.images[0]?.url.startsWith("data:")).length;
  process.stdout.write(
    `\n  ${ingest.catalogue.products.length} products, ${photos} with photographs, ` +
      `${ingest.catalogue.products.length - photos} still drawn.\n\n`,
  );

  for (const edit of EDITS) {
    const { config } = await merchandise(ingest, edit.prompt);
    await saveShop(edit.slug, {
      config,
      catalogue: ingest.catalogue,
      ingestedAt: ingest.store.ingestedAt,
    });

    const chosen = config.blocks
      .flatMap((b) => ("products" in b.block ? (b.block.products as { handle: string }[]) : []))
      .length;
    process.stdout.write(
      `  ${edit.slug.padEnd(14)} ${String(chosen).padStart(2)} products  ${config.theme.mood.padEnd(10)} ${config.theme.colorway.accent}\n`,
    );
  }

  process.stdout.write(
    "\n  Written to .cache/shop/. Capture them with `pnpm press:capture-edits`,\n" +
      "  then freeze with `pnpm tsx scripts/demo-fixtures.ts`.\n\n",
  );
}

await main();
