// Demo data: `npm run seed`.
//
// Creates a Pro account with three published widgets and a fortnight of
// plausible traffic, so the dashboard, the analytics page and the lead table
// all have something real in them the first time you open them.
//
// Traffic is generated by walking the funnel with realistic drop-off, not by
// writing totals into a table — the numbers on screen are rolled up from
// events exactly as production's would be.

import { getStore } from "../src/lib/db/store";
import { hashPassword } from "../src/lib/auth/password";
import { createWidgetFor, isLimitError } from "../src/lib/widgets/service";
import { TEMPLATES, templateBySlug } from "../src/lib/templates/catalogue";
import { defaultAnswers, evaluateWidget } from "../src/lib/widget/engine";

const EMAIL = "demo@mekmi.test";
const PASSWORD = "demo-password";

const SEEDED = ["cleaning-estimate", "skincare-finder", "website-project-quote"];

/** Deterministic pseudo-random, so `npm run seed` twice gives the same demo. */
function makeRandom(seed: number) {
  let state = seed;
  return () => {
    state = (state * 1664525 + 1013904223) % 4294967296;
    return state / 4294967296;
  };
}

async function main() {
  const store = getStore();

  let user = await store.findUserByEmail(EMAIL);
  if (!user) {
    user = await store.createUser({ email: EMAIL, passwordHash: await hashPassword(PASSWORD) });
  }
  // Pro, so lead capture and analytics are visible in the demo (§35).
  await store.setUserPlan(user.id, "pro");

  const existing = await store.listWidgets(user.id);
  if (existing.length > 0) {
    console.log(`${EMAIL} already has ${existing.length} widgets — nothing to do.`);
    console.log(`Sign in with ${EMAIL} / ${PASSWORD}`);
    return;
  }

  const random = makeRandom(20260810);

  for (const slug of SEEDED) {
    const template = templateBySlug(slug);
    if (!template) continue;

    const created = await createWidgetFor(user.id, "pro", structuredClone(template.document));
    if (isLimitError(created)) {
      console.error(created.message);
      continue;
    }
    await store.publishWidget(created.id);

    const document = template.document;
    const steps = document.steps;
    let views = 0;
    let completions = 0;
    let leads = 0;

    for (let day = 13; day >= 0; day -= 1) {
      const sessions = 12 + Math.floor(random() * 26);
      // Spread the demo traffic over a fortnight so the daily chart has a
      // shape, rather than one spike on the day you ran the script.
      const stamp = new Date();
      stamp.setUTCDate(stamp.getUTCDate() - day);
      stamp.setUTCHours(9 + Math.floor(random() * 9), 0, 0, 0);
      const createdAt = stamp.toISOString();

      for (let visit = 0; visit < sessions; visit += 1) {
        const session = `seed_${slug}_${day}_${visit}`;
        const events = [{ widgetId: created.id, sessionId: session, type: "widget_view", createdAt }];
        views += 1;

        // ~72% start, then a small chance of leaving at each question.
        if (random() < 0.72) {
          events.push({ widgetId: created.id, sessionId: session, type: "widget_start", createdAt });

          let reached = 0;
          for (const step of steps) {
            if (random() < 0.09) break;
            events.push({
              widgetId: created.id,
              sessionId: session,
              type: "step_complete",
              stepId: step.id,
              createdAt,
            } as never);
            reached += 1;
          }

          if (reached === steps.length) {
            events.push({ widgetId: created.id, sessionId: session, type: "widget_complete", createdAt });
            events.push({ widgetId: created.id, sessionId: session, type: "result_view", createdAt });
            completions += 1;

            if (random() < 0.21) {
              events.push({ widgetId: created.id, sessionId: session, type: "cta_click", createdAt });
            }

            if (random() < 0.14 && document.settings.leadCapture.mode !== "none") {
              events.push({ widgetId: created.id, sessionId: session, type: "lead_submit", createdAt });
              const answers = plausibleAnswers(document, random);
              const evaluation = evaluateWidget(document, answers);
              await store.createLead({
                widgetId: created.id,
                name: NAMES[Math.floor(random() * NAMES.length)],
                email: `visitor${leads + 1}@example.com`,
                metadata: { answers, result: evaluation.display, outcome: evaluation.outcome?.title ?? null },
                // The same day-stamp the events carry. Without it every demo
                // enquiry landed today while the traffic that produced them
                // was spread over a fortnight.
                createdAt,
              });
              leads += 1;
            }
          }
        }

        await store.recordEvents(events as never);
      }
    }

    console.log(
      `${template.name}: ${views} views, ${completions} completions, ${leads} enquiries`
    );
  }

  console.log(`\nSeeded. Sign in with ${EMAIL} / ${PASSWORD}`);
}

const NAMES = ["Ada", "Bilal", "Cara", "Dev", "Eve", "Femi", "Gus", "Hana", "Ines", "Jo"];

/** Pick a real answer for each question, so leads carry believable context. */
function plausibleAnswers(
  document: (typeof TEMPLATES)[number]["document"],
  random: () => number
): Record<string, unknown> {
  const answers = defaultAnswers(document);

  for (const step of document.steps) {
    switch (step.input.kind) {
      case "choice": {
        const options = step.input.options;
        const pick = options[Math.floor(random() * options.length)];
        answers[step.id] = step.input.multiple ? (random() < 0.5 ? [pick.value] : []) : pick.value;
        break;
      }
      case "slider": {
        const { min, max } = step.input;
        answers[step.id] = Math.round(min + random() * (max - min));
        break;
      }
      case "number":
        answers[step.id] = Math.round(random() * 2000);
        break;
      case "toggle":
        answers[step.id] = random() < 0.4;
        break;
      default:
        break;
    }
  }
  return answers;
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
