/**
 * The front door.
 *
 * A landing page is the surface most likely to drift away from what the
 * product does, because nothing breaks when it does. These are the three ways
 * this one could start lying, held as invariants rather than as good
 * intentions in a comment.
 *
 * It is deliberately not a test of the copy. Wording should be free to change;
 * what should not is the page acquiring a form that goes nowhere, promising a
 * sign-up that does not exist, or showing a screenshot that is no longer in
 * the repository.
 */

import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import Landing from "@/app/page";

const PUBLIC = path.join(process.cwd(), "public");
const html = renderToStaticMarkup(<Landing />);

/** Every `src` the page asks the browser for. */
const sources = [...html.matchAll(/src="([^"]+)"/g)].map((match) => match[1]!);

/**
 * The page as somebody reads it, one sentence at a time.
 *
 * The first version of the claim test matched words against the whole
 * document and failed on "nothing here syncs with your store" — which is the
 * page keeping the rule, not breaking it. A claim is a sentence, so the unit
 * has to be a sentence.
 */
const sentences = html
  .replace(/<[^>]+>/g, " ")
  .replace(/&[a-z]+;/g, " ")
  .replace(/\s+/g, " ")
  .split(/(?<=[.!?])\s+/)
  .map((sentence) => sentence.trim())
  .filter(Boolean);

const DENIES = /\b(no|not|nothing|never|without|isn't|does not|do not)\b/i;

describe("the landing page", () => {
  it("is not gated on the workbench", () => {
    // The workbench 404s in a production build. This must not: it is the page
    // a merchant reaches by trimming their own shop link, and the gate lived
    // at this path until the landing page took it.
    expect(html).toContain("popuup");
    expect(html.length).toBeGreaterThan(2000);
  });

  it("asks for an email by opening a mail client, not by collecting one", () => {
    // Email capture is Sprint 3 and gated on the kill test. A form that posted
    // nowhere would look identical to a working one right up until somebody
    // used it.
    expect(html).toMatch(/href="mailto:[^"]+"/);
    expect(html).not.toContain("<form");
    expect(html).not.toContain("<input");
    expect(html).not.toContain("<button");
  });

  it("does not promise an account, a dashboard or a price", () => {
    const promises = [/sign ?up/i, /log ?in/i, /free trial/i, /per month/i, /\$\d/, /£\d/];
    const status = html.slice(html.indexOf("Where this is"));

    for (const promise of promises) {
      // The status section is allowed to say these words, because saying "there
      // is no sign-up" is the opposite of promising one.
      const outsideStatus = html.replace(status, "");
      expect(outsideStatus, `${promise} appears outside the status section`).not.toMatch(promise);
    }
  });

  it("only mentions sync or liveness in order to deny it", () => {
    // The rule the shop template works under, applied to the page that sells
    // it: nothing may claim sync or liveness that is not wired. Saying "nothing
    // here syncs with your store" keeps that rule; this checks the sentence,
    // because a word list cannot tell the two apart.
    // "live" is deliberately not in here. In this codebase it means published
    // — the kill test counts merchants who want their shop live — and folding
    // that into a freshness check turns the test into a vocabulary argument
    // rather than an honesty one. What is being guarded is claims about the
    // catalogue staying current, which is the thing that is not wired.
    const liveness = /\b(sync\w*|real[- ]?time|up to date|automatic\w*|always current)\b/i;

    for (const sentence of sentences.filter((s) => liveness.test(s))) {
      expect(sentence, "says something about liveness without denying it").toMatch(DENIES);
    }
  });

  it("counts nobody it has not got", () => {
    // The two claims a pre-launch page reaches for first, and the two it has
    // least right to.
    expect(html).not.toMatch(/\btrusted by\b/i);
    expect(html).not.toMatch(/\b\d[\d,]*\+? (merchants|stores|shops|brands)\b/i);
    expect(html).not.toMatch(/\b(instantly|in seconds)\b/i);
  });

  it("only shows images that are actually in the repository", () => {
    // The screenshots are generated by `pnpm press` into `public/press`. If one
    // is renamed or a mood is dropped, this page would render a broken image
    // in production and nothing else would notice.
    expect(sources.length).toBeGreaterThan(0);

    for (const src of sources) {
      expect(src.startsWith("/"), `${src} is not a local asset`).toBe(true);
      expect(existsSync(path.join(PUBLIC, src)), `public${src} is missing`).toBe(true);
    }
  });

  it("does not borrow a class name the shop template already owns", () => {
    /*
     * Two design systems, one global namespace.
     *
     * `shop.css` is imported by the root layout, so every rule in it applies
     * to the landing page too. The landing page used `.hero`, `.hero-copy` and
     * `.eyebrow` — all three of which the shop template styles — and it went
     * unnoticed for as long as both were white text on a dark ground. The
     * moment the page moved onto cream, `.hero-copy { color: #fff }` from the
     * other stylesheet made the headline invisible against its own background.
     *
     * The failure mode is what makes this worth a test: nothing errors, both
     * files are individually correct, and the damage only appears in a browser
     * at one specific combination of the two. So the rule is separation by
     * name — the landing page may not use a selector the shop owns.
     */
    const selectorsIn = (file: string): Set<string> => {
      const css = readFileSync(path.join(process.cwd(), "src/app", file), "utf8").replace(/\/\*[\s\S]*?\*\//g, " ");
      const found = new Set<string>();
      for (const [, selector] of css.matchAll(/([^{}]+)\{/g)) {
        for (const [, name] of selector!.matchAll(/\.([A-Za-z_][\w-]*)/g)) found.add(name!);
      }
      return found;
    };

    const shop = selectorsIn("shop.css");
    expect(shop.size).toBeGreaterThan(20);

    // What the page actually puts in the DOM, rather than what the stylesheet
    // happens to mention — an unstyled class still inherits the other file's.
    const used = new Set([...html.matchAll(/class="([^"]*)"/g)].flatMap((m) => m[1]!.split(/\s+/)).filter(Boolean));
    expect(used.size).toBeGreaterThan(10);

    expect([...used].filter((name) => shop.has(name))).toEqual([]);
  });

  it("shows the wordmark as the generated file, not a second drawing of it", () => {
    /*
     * Two copies of a logo is how a logo ends up with two letterspacings.
     * `scripts/press/logo.mjs` writes both colourways from one geometry, and
     * that agreement is what this test is really for.
     *
     * It used to also require the *light* colourway on this page, which was a
     * fact about the old design rather than about the wordmark: the foot sat in
     * an ink band. Every page now closes on lilac, so both marks on the page
     * are the dark one — and asserting the light file appears would have meant
     * shipping a pale smudge on a pale ground to keep a test green. The check
     * that survives is the one that matters: the page uses a generated file,
     * and the two files are the same drawing.
     */
    expect(sources.filter((src) => src.startsWith("/brand/")).length).toBeGreaterThan(0);
    for (const src of sources.filter((s) => s.startsWith("/brand/"))) {
      expect(src, "the wordmark must be an svg from scripts/press/logo.mjs").toMatch(/^\/brand\/popuup(-light)?\.svg$/);
    }

    const light = readFileSync(path.join(PUBLIC, "brand/popuup-light.svg"), "utf8");
    const dark = readFileSync(path.join(PUBLIC, "brand/popuup.svg"), "utf8");
    const paths = (svg: string) => [...svg.matchAll(/ d="([^"]+)"/g)].map((match) => match[1]);

    expect(paths(light)).toEqual(paths(dark));
    expect(paths(light).length).toBeGreaterThan(4);
  });
});
