/**
 * What produced a shop, and whether it survives being written down.
 *
 * The build brief calls this dataset the moat and says it is "unrecoverable if
 * not captured now" — so the assertions here are less about the code being
 * elegant than about a real run not silently recording nulls.
 */

import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { createLocalStore, publishShop } from "@/lib/publish/index";
import type { ShopStore } from "@/lib/publish/store";
import { promptFingerprint, genomeVersionOf } from "@/lib/provenance";
import { PROMPT_VERSION as MERCHANDISE_PROMPT_VERSION, SYSTEM_PROMPT as MERCHANDISE_SYSTEM } from "@/lib/merchandise/prompt";
import { PROMPT_VERSION as GENOME_PROMPT_VERSION, SYSTEM_PROMPT as GENOME_SYSTEM } from "@/lib/genome/prompt";
import { makeIngest } from "./helpers/ingest";
import { buildPlan } from "@/lib/merchandise/mock";
import { assembleShopConfig } from "@/lib/merchandise/assemble";

describe("promptFingerprint", () => {
  it("is stable for the same text", () => {
    expect(promptFingerprint("hello")).toBe(promptFingerprint("hello"));
  });

  it("changes on any edit, including whitespace", () => {
    // The whole reason this is derived rather than hand-set: an edit nobody
    // remembers to version is still an edit, and a shop generated after it was
    // generated by different instructions.
    expect(promptFingerprint("hello")).not.toBe(promptFingerprint("hello "));
    expect(promptFingerprint("hello")).not.toBe(promptFingerprint("Hello"));
  });

  it("is short enough to read and long enough not to collide", () => {
    expect(promptFingerprint("x")).toHaveLength(12);
    expect(promptFingerprint("x")).toMatch(/^[0-9a-f]{12}$/);
  });
});

describe("the exported prompt versions", () => {
  it("describe the prompts they sit beside", () => {
    // If either of these ever drifts, the fingerprint is describing text other
    // than the text that was sent — which is worse than not recording one.
    expect(MERCHANDISE_PROMPT_VERSION).toBe(promptFingerprint(MERCHANDISE_SYSTEM));
    expect(GENOME_PROMPT_VERSION).toBe(promptFingerprint(GENOME_SYSTEM));
  });

  it("are different from each other", () => {
    expect(MERCHANDISE_PROMPT_VERSION).not.toBe(GENOME_PROMPT_VERSION);
  });
});

describe("publishing", () => {
  let dir: string;
  let store: ShopStore;

  beforeEach(async () => {
    dir = await mkdtemp(path.join(tmpdir(), "popuup-provenance-"));
    store = createLocalStore({ dir });
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  const shop = () => {
    const ingest = makeIngest();
    const plan = buildPlan(ingest, "a gift edit");
    return {
      ingest,
      config: assembleShopConfig({ ingest, plan, prompt: "a gift edit", now: new Date("2026-08-13T09:00:00.000Z") }).config,
    };
  };

  it("records what produced the version", async () => {
    const { ingest, config } = shop();
    await publishShop(
      {
        config,
        ingest,
        slug: "kelp",
        provenance: {
          model: "claude-opus-5",
          promptVersion: MERCHANDISE_PROMPT_VERSION,
          genomeVersion: genomeVersionOf("claude-sonnet-5", GENOME_PROMPT_VERSION),
        },
      },
      { store },
    );

    const shopRecord = await store.findShopBySlug("kelp");
    const versions = await store.listPublished();
    expect(versions).toHaveLength(1);

    // Read back through the store rather than asserting on what was passed in,
    // because the thing being tested is that it survived the write.
    const written = await store.addVersion({
      shopId: shopRecord!.id,
      config,
      prompt: "second",
      audience: null,
      model: "claude-opus-5",
      promptVersion: MERCHANDISE_PROMPT_VERSION,
      genomeVersion: genomeVersionOf("claude-sonnet-5", GENOME_PROMPT_VERSION),
    });
    expect(written.model).toBe("claude-opus-5");
    expect(written.promptVersion).toBe(MERCHANDISE_PROMPT_VERSION);
    expect(written.genomeVersion).toBe(`claude-sonnet-5/${GENOME_PROMPT_VERSION}`);
  });

  it("records nulls rather than guesses when the caller does not know", async () => {
    // A test or a hand-assembled config has no honest answer, and an invented
    // one would poison the dataset more quietly than a null does.
    const { ingest, config } = shop();
    await publishShop({ config, ingest, slug: "kelp" }, { store });

    const shopRecord = await store.findShopBySlug("kelp");
    const written = await store.addVersion({
      shopId: shopRecord!.id,
      config,
      prompt: "no provenance",
      audience: null,
    });
    expect(written.model).toBeNull();
    expect(written.promptVersion).toBeNull();
    expect(written.genomeVersion).toBeNull();
  });

  it("keeps a version's provenance when a later version is added", async () => {
    // Regeneration appends; the funnel events attributed to v1 must still point
    // at the model and prompt that made v1.
    const { ingest, config } = shop();
    await publishShop(
      { config, ingest, slug: "kelp", provenance: { model: "first-model", promptVersion: "aaaaaaaaaaaa", genomeVersion: null } },
      { store },
    );
    await publishShop(
      { config, ingest, slug: "kelp", provenance: { model: "second-model", promptVersion: "bbbbbbbbbbbb", genomeVersion: null } },
      { store },
    );

    // Read the local store's file directly. White-box, deliberately: the store
    // interface exposes only the *current* version, and the property under
    // test is that the superseded one still carries its own provenance. There
    // is no read path for shop history yet, and adding one to satisfy a test
    // would be adding API surface for a reason that is not a product need.
    const { readFile } = await import("node:fs/promises");
    const db = JSON.parse(await readFile(path.join(dir, "db.json"), "utf8")) as {
      versions: { model: string | null; promptVersion: string | null }[];
    };
    expect(db.versions.map((v) => v.model)).toEqual(["first-model", "second-model"]);
    expect(db.versions.map((v) => v.promptVersion)).toEqual(["aaaaaaaaaaaa", "bbbbbbbbbbbb"]);
  });
});
