/**
 * Activity taxonomy (§9 screens 6 and 7).
 *
 * Kept extensible: a category is a row here, not a union baked into fifty
 * switch statements. Each carries the properties the hard filters and scorers
 * actually need — whether it is weather-proof, how exposed it is, how much it
 * typically costs, which child ages it works for — so adding "wildlife park"
 * later means adding one entry, not editing the planner.
 */

export type CategoryId = string;

export interface Category {
  id: CategoryId;
  /** Customer-facing label. Sentence case; these appear on chips. */
  label: string;
  /** Grouping for the onboarding grid. */
  group: "outdoors" | "food" | "culture" | "active" | "family" | "explore";
  /** Usable in rain without a miserable experience. */
  weatherproof: boolean;
  /** 0 = fully sheltered, 1 = fully exposed to sun and wind. */
  exposure: number;
  /** Typical spend band per adult; 0 = free. Used before we have real prices. */
  typical_cost_band: 0 | 1 | 2 | 3;
  /** Physical demand of the category itself, before distance is considered. */
  intensity: "GENTLE" | "EASY" | "MODERATE" | "ACTIVE";
  /** Minimum child age in years this is generally suitable for. 0 = any age. */
  min_child_age: number;
  /** Categories that can anchor a plan rather than merely accompany one. */
  can_anchor: boolean;
  /** Tends to be busy. Cross-referenced with crowd tolerance. */
  typically_busy: boolean;
  /** Search phrasing hints handed to the intent generator (§14). */
  search_hints: readonly string[];
}

export const CATEGORIES: readonly Category[] = [
  {
    id: "beaches",
    label: "Beaches",
    group: "outdoors",
    weatherproof: false,
    exposure: 1,
    typical_cost_band: 0,
    intensity: "GENTLE",
    min_child_age: 0,
    can_anchor: true,
    typically_busy: true,
    search_hints: ["beach", "harbour beach", "swimming beach"],
  },
  {
    id: "waterfront",
    label: "Waterfront",
    group: "outdoors",
    weatherproof: false,
    exposure: 0.8,
    typical_cost_band: 0,
    intensity: "EASY",
    min_child_age: 0,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["waterfront walk", "harbour foreshore", "coastal path"],
  },
  {
    id: "bushwalks",
    label: "Bushwalks",
    group: "active",
    weatherproof: false,
    exposure: 0.5,
    typical_cost_band: 0,
    intensity: "MODERATE",
    min_child_age: 5,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["bushwalk", "national park walking track", "nature trail"],
  },
  {
    id: "easy_walks",
    label: "Easy walks",
    group: "active",
    weatherproof: false,
    exposure: 0.6,
    typical_cost_band: 0,
    intensity: "EASY",
    min_child_age: 0,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["easy walk", "flat walking path", "promenade"],
  },
  {
    id: "markets",
    label: "Markets",
    group: "explore",
    weatherproof: false,
    exposure: 0.4,
    typical_cost_band: 1,
    intensity: "EASY",
    min_child_age: 0,
    can_anchor: true,
    typically_busy: true,
    search_hints: ["weekend market", "farmers market", "growers market"],
  },
  {
    id: "food",
    label: "Food",
    group: "food",
    weatherproof: true,
    exposure: 0.1,
    typical_cost_band: 2,
    intensity: "GENTLE",
    min_child_age: 0,
    can_anchor: false,
    typically_busy: false,
    search_hints: ["restaurant", "lunch"],
  },
  {
    id: "bakeries",
    label: "Bakeries",
    group: "food",
    weatherproof: true,
    exposure: 0.1,
    typical_cost_band: 1,
    intensity: "GENTLE",
    min_child_age: 0,
    can_anchor: false,
    typically_busy: false,
    search_hints: ["bakery", "pastry"],
  },
  {
    id: "coffee",
    label: "Great coffee",
    group: "food",
    weatherproof: true,
    exposure: 0.1,
    typical_cost_band: 1,
    intensity: "GENTLE",
    min_child_age: 0,
    can_anchor: false,
    typically_busy: false,
    search_hints: ["specialty coffee", "cafe"],
  },
  {
    id: "neighbourhoods",
    label: "Hidden neighbourhoods",
    group: "explore",
    weatherproof: false,
    exposure: 0.5,
    typical_cost_band: 1,
    intensity: "EASY",
    min_child_age: 0,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["village high street", "neighbourhood shops", "laneways"],
  },
  {
    id: "culture",
    label: "Culture",
    group: "culture",
    weatherproof: true,
    exposure: 0.1,
    typical_cost_band: 1,
    intensity: "GENTLE",
    min_child_age: 4,
    can_anchor: true,
    typically_busy: true,
    search_hints: ["cultural centre", "exhibition"],
  },
  {
    id: "galleries",
    label: "Galleries",
    group: "culture",
    weatherproof: true,
    exposure: 0,
    typical_cost_band: 1,
    intensity: "GENTLE",
    min_child_age: 6,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["art gallery", "contemporary art"],
  },
  {
    id: "museums",
    label: "Museums",
    group: "culture",
    weatherproof: true,
    exposure: 0,
    typical_cost_band: 2,
    intensity: "GENTLE",
    min_child_age: 3,
    can_anchor: true,
    typically_busy: true,
    search_hints: ["museum"],
  },
  {
    id: "gardens",
    label: "Gardens",
    group: "outdoors",
    weatherproof: false,
    exposure: 0.7,
    typical_cost_band: 0,
    intensity: "GENTLE",
    min_child_age: 0,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["botanic garden", "public garden", "arboretum"],
  },
  {
    id: "animals",
    label: "Animals",
    group: "family",
    weatherproof: false,
    exposure: 0.6,
    typical_cost_band: 2,
    intensity: "EASY",
    min_child_age: 0,
    can_anchor: true,
    typically_busy: true,
    search_hints: ["wildlife park", "aquarium", "city farm"],
  },
  {
    id: "ferries",
    label: "Ferries",
    group: "explore",
    weatherproof: false,
    exposure: 0.6,
    typical_cost_band: 1,
    intensity: "GENTLE",
    min_child_age: 0,
    can_anchor: false,
    typically_busy: false,
    search_hints: ["ferry wharf", "harbour ferry"],
  },
  {
    id: "trains",
    label: "Trains",
    group: "explore",
    weatherproof: true,
    exposure: 0.2,
    typical_cost_band: 1,
    intensity: "GENTLE",
    min_child_age: 0,
    can_anchor: false,
    typically_busy: false,
    search_hints: ["scenic railway", "heritage railway"],
  },
  {
    id: "playgrounds",
    label: "Playgrounds",
    group: "family",
    weatherproof: false,
    exposure: 0.8,
    typical_cost_band: 0,
    intensity: "EASY",
    min_child_age: 0,
    can_anchor: false,
    typically_busy: false,
    search_hints: ["playground", "adventure playground"],
  },
  {
    id: "swimming",
    label: "Swimming",
    group: "active",
    weatherproof: false,
    exposure: 0.9,
    typical_cost_band: 1,
    intensity: "EASY",
    min_child_age: 0,
    can_anchor: true,
    typically_busy: true,
    search_hints: ["ocean pool", "swimming pool", "rock pool"],
  },
  {
    id: "cycling",
    label: "Cycling",
    group: "active",
    weatherproof: false,
    exposure: 0.9,
    typical_cost_band: 0,
    intensity: "MODERATE",
    min_child_age: 6,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["cycleway", "bike path"],
  },
  {
    id: "unusual",
    label: "Unusual experiences",
    group: "explore",
    weatherproof: true,
    exposure: 0.3,
    typical_cost_band: 2,
    intensity: "EASY",
    min_child_age: 6,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["unusual attraction", "quirky experience"],
  },
  {
    id: "workshops",
    label: "Workshops",
    group: "culture",
    weatherproof: true,
    exposure: 0,
    typical_cost_band: 3,
    intensity: "GENTLE",
    min_child_age: 6,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["pottery class", "craft workshop", "cooking class"],
  },
  {
    id: "live_music",
    label: "Live music",
    group: "culture",
    weatherproof: true,
    exposure: 0.2,
    typical_cost_band: 2,
    intensity: "GENTLE",
    min_child_age: 8,
    can_anchor: true,
    typically_busy: true,
    search_hints: ["live music venue", "afternoon session"],
  },
  {
    id: "scenic_drives",
    label: "Scenic drives",
    group: "explore",
    weatherproof: true,
    exposure: 0.2,
    typical_cost_band: 1,
    intensity: "GENTLE",
    min_child_age: 0,
    can_anchor: false,
    typically_busy: false,
    search_hints: ["lookout", "scenic drive"],
  },
  {
    id: "picnics",
    label: "Picnics",
    group: "outdoors",
    weatherproof: false,
    exposure: 0.8,
    typical_cost_band: 1,
    intensity: "GENTLE",
    min_child_age: 0,
    can_anchor: false,
    typically_busy: false,
    search_hints: ["picnic area", "park with tables"],
  },
  {
    id: "sport",
    label: "Sport",
    group: "active",
    weatherproof: false,
    exposure: 0.7,
    typical_cost_band: 2,
    intensity: "MODERATE",
    min_child_age: 5,
    can_anchor: true,
    typically_busy: true,
    search_hints: ["sports ground", "match"],
  },
  {
    id: "wellness",
    label: "Wellness",
    group: "active",
    weatherproof: true,
    exposure: 0.1,
    typical_cost_band: 3,
    intensity: "GENTLE",
    min_child_age: 12,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["bathhouse", "yoga studio", "day spa"],
  },
  {
    id: "vintage",
    label: "Vintage & antiques",
    group: "explore",
    weatherproof: true,
    exposure: 0.2,
    typical_cost_band: 1,
    intensity: "GENTLE",
    min_child_age: 8,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["vintage store", "antique centre", "op shop"],
  },
  {
    id: "architecture",
    label: "Architecture",
    group: "culture",
    weatherproof: false,
    exposure: 0.5,
    typical_cost_band: 0,
    intensity: "EASY",
    min_child_age: 8,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["notable building", "architecture walk"],
  },
  {
    id: "history",
    label: "History",
    group: "culture",
    weatherproof: false,
    exposure: 0.4,
    typical_cost_band: 1,
    intensity: "EASY",
    min_child_age: 6,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["historic site", "heritage building"],
  },
  {
    id: "day_trips",
    label: "Day trips",
    group: "explore",
    weatherproof: false,
    exposure: 0.5,
    typical_cost_band: 2,
    intensity: "EASY",
    min_child_age: 3,
    can_anchor: true,
    typically_busy: false,
    search_hints: ["day trip town", "regional village"],
  },
];

const BY_ID = new Map(CATEGORIES.map((c) => [c.id, c]));

export function category(id: CategoryId): Category | undefined {
  return BY_ID.get(id);
}

export function categoriesInGroup(group: Category["group"]): Category[] {
  return CATEGORIES.filter((c) => c.group === group);
}

export function anchorCategories(): Category[] {
  return CATEGORIES.filter((c) => c.can_anchor);
}

/** Dislikes (§9 screen 7). Modelled separately: these are constraints, not tastes. */
export const DISLIKES = [
  { id: "crowds", label: "Crowds" },
  { id: "early_mornings", label: "Early mornings" },
  { id: "long_drives", label: "Long drives" },
  { id: "expensive_restaurants", label: "Expensive restaurants" },
  { id: "steep_hikes", label: "Steep hikes" },
  { id: "shopping", label: "Shopping" },
  { id: "noisy_venues", label: "Noisy venues" },
  { id: "queues", label: "Queues" },
  { id: "touristy", label: "Touristy places" },
] as const;

export type DislikeId = (typeof DISLIKES)[number]["id"];

/** Cuisines (§9 screen 8). Not exhaustive; free text is also accepted. */
export const CUISINES = [
  "Australian",
  "Italian",
  "Japanese",
  "Chinese",
  "Vietnamese",
  "Thai",
  "Korean",
  "Indian",
  "Middle Eastern",
  "Greek",
  "Mexican",
  "Spanish",
  "French",
  "Seafood",
  "Vegetarian",
  "Modern Asian",
  "Pub food",
] as const;

export const DIETARY_REQUIREMENTS = [
  "vegetarian",
  "vegan",
  "gluten_free",
  "dairy_free",
  "nut_allergy",
  "halal",
  "kosher",
  "pescatarian",
] as const;
