// The pages a search engine may have.
//
// robots.ts has advertised /sitemap.xml since the sharing work went in, and
// nothing served it. A 404 there is harmless, but the reason to write it now
// is that the promise page is the first page we actively want found: it is
// the document a parent looks for when deciding whether to trust this, and
// it is the one thing here worth being findable.
//
// Listed explicitly, never generated by walking the route tree. A generator
// that enumerated src/app would happily publish /subjects/[subjectId] the
// day somebody made it statically renderable, and a sitemap is a machine
// telling every crawler in the world where to look. The list is short
// because the public surface is small; that is a property of the product,
// not an oversight.

import type { MetadataRoute } from "next";
import { BASE, OFF_LIMITS } from "./robots";
import { published } from "@/lib/journal/entries";

/** Public pages, in rough order of how much we want them found. */
export const PUBLIC_PAGES = [
  "/", "/about", "/promise", "/privacy", "/pricing", "/help", "/journal",
] as const;

export default function sitemap(): MetadataRoute.Sitemap {
  const fixed = PUBLIC_PAGES.filter(
    // Belt and braces against the two files disagreeing. A page that robots
    // forbids must never appear here, whatever anybody adds above.
    (path) => !OFF_LIMITS.some((blocked) => path.startsWith(blocked))
  ).map((path) => ({
    url: `${BASE}${path === "/" ? "" : path}`,
    changeFrequency: "monthly" as const,
    priority: path === "/" ? 1 : 0.7,
  }));

  // Journal entries, from the same published() list the index and the feed
  // read — so a draft cannot be absent from one and announced in another.
  // lastModified is the real date, never the deploy: a page claiming to have
  // changed today because it was built today is lying to a search engine and
  // to a reader in the same breath.
  const journal = published().map((e) => ({
    url: `${BASE}/journal/${e.slug}`,
    lastModified: new Date(e.updated ?? e.published),
    changeFrequency: "yearly" as const,
    priority: 0.6,
  }));

  return [...fixed, ...journal];
}
