/**
 * Validated rules → the SQL that puts them in the `rules` table.
 *
 * Generated, never hand-edited: `pnpm rules:sql` writes `supabase/seed.sql`
 * from the YAML, and `tests/rules-seed.test.ts` fails when the committed file
 * and the YAML disagree. The upsert keys on the permanent rule id, so applying
 * it twice is harmless and applying it after an edit updates the row in place.
 *
 * Rules are written by the service role only. No policy lets a merchant write
 * to `rules`, and nothing a model produces is ever passed to this function
 * (BUILD_BRIEF.md §6: "never let model output write directly to rules").
 */

import { ruleId, type Rule } from "../engine/rules.js";
import type { RulesSnapshot } from "../engine/snapshot.js";

function literal(value: string | null): string {
  return value === null ? "null" : `'${value.replace(/'/g, "''")}'`;
}

function jsonb(value: unknown): string {
  return `${literal(JSON.stringify(value))}::jsonb`;
}

function row(rule: Rule): string {
  const { regulation, article, url, effective_from, effective_to } = rule.citation;
  return `(${[
    literal(ruleId(rule)),
    literal(rule.market),
    literal(rule.category),
    literal(rule.rule_key),
    literal(rule.kind),
    literal(rule.title),
    literal(rule.fix),
    jsonb(rule.params),
    rule.applies_if ? jsonb(rule.applies_if) : "null",
    literal(rule.severity),
    jsonb({ regulation, article, url, effective_from, ...(effective_to ? { effective_to } : {}) }),
    literal(rule.confidence),
    String(rule.version),
  ].join(", ")})`;
}

export function seedSql(snapshot: RulesSnapshot): string {
  const lines = [
    "-- Generated by `pnpm rules:sql` from rules/**/*.yaml. Do not edit by hand.",
    `-- Rules snapshot ${snapshot.version}, ${snapshot.rules.length} rules.`,
    "",
    "begin;",
    "",
  ];
  if (snapshot.rules.length > 0) {
    lines.push(
      "insert into public.rules (id, market_code, category, rule_key, kind, title, fix, params, applies_if, severity, citation, confidence, version)",
      "values",
      snapshot.rules.map((r) => `  ${row(r)}`).join(",\n"),
      "on conflict (id) do update set",
      "  market_code = excluded.market_code, category = excluded.category, rule_key = excluded.rule_key,",
      "  kind = excluded.kind, title = excluded.title, fix = excluded.fix, params = excluded.params,",
      "  applies_if = excluded.applies_if, severity = excluded.severity, citation = excluded.citation,",
      "  confidence = excluded.confidence, version = excluded.version, updated_at = now();",
      "",
    );
  }
  lines.push(
    "-- A rule deleted from the YAML is retired, not deleted: assessments that",
    "-- cite it must still resolve. Retired rules are never loaded into a snapshot.",
    `update public.rules set retired_at = now() where retired_at is null and id not in (${
      snapshot.rules.length > 0 ? snapshot.rules.map((r) => literal(ruleId(r))).join(", ") : "''"
    });`,
    `update public.rules set retired_at = null where id in (${
      snapshot.rules.length > 0 ? snapshot.rules.map((r) => literal(ruleId(r))).join(", ") : "''"
    });`,
    "",
    "commit;",
    "",
  );
  return lines.join("\n");
}
