/**
 * Booting a real browser over a real shop.
 *
 * The vitest suite runs in jsdom, which has no layout engine: nothing in it can
 * observe an `aspect-ratio` resolving against a container width, a grid
 * collapsing to one column, or a label rendering white on white. Those are the
 * regressions this file exists to make catchable, and catching them needs a
 * browser that actually lays the page out.
 *
 * The shop under test is built by the real pipeline — ingest the fixture
 * storefront, merchandise it, save it through the same store the route reads —
 * so an assertion here is about the renderer rather than about a hand-written
 * config shaped to pass.
 */

import { spawn, type ChildProcess } from "node:child_process";
import net from "node:net";
import { existsSync } from "node:fs";
import { readFile, rm } from "node:fs/promises";
import path from "node:path";
import { chromium, type Browser, type Page } from "playwright-core";
import { ingestStore } from "@/lib/ingest/index";
import { merchandise } from "@/lib/merchandise/index";
import { createMockProvider } from "@/lib/merchandise/mock";
import { saveShop } from "@/lib/render/store";
import type { ShopConfig } from "@/lib/schema";
import { startFixtureStore, type FixtureStore } from "./fixture-store";

export const MOODS = ["clean", "editorial", "playful", "luxe", "utility"] as const;
export type Mood = (typeof MOODS)[number];

/** Non-bleed moods keep a plated hero; the rest run to the glass. */
export const PLATED_MOODS: Mood[] = ["clean", "utility"];

export interface Viewport {
  width: number;
  height: number;
  label: string;
}

export const PHONE: Viewport = { width: 390, height: 844, label: "390x844" };
export const DESKTOPS: Viewport[] = [
  { width: 1440, height: 900, label: "1440x900" },
  { width: 1280, height: 800, label: "1280x800" },
];

/**
 * Keys are prefixed so a run cannot collide with a shop somebody generated by
 * hand, and so teardown can delete its own files and nothing else.
 */
const KEY_PREFIX = "geometry-";
const keyFor = (mood: Mood) => `${KEY_PREFIX}${mood}`;
export const urlFor = (base: string, mood: Mood) => `${base}/preview/${keyFor(mood)}`;

/**
 * The browser is the one thing here that cannot be installed on demand.
 *
 * Two ways to find one, in order. An explicit `CHROMIUM_PATH` wins, because a
 * developer with a Chromium already on disk should not be made to download a
 * second one. Otherwise ask playwright-core where its own registry put the
 * browser that `playwright install chromium` fetches — which is how CI finds
 * it, and how a developer who ran that command does too.
 *
 * `executablePath()` answers from the registry whether or not the download
 * ever happened, so the answer is only useful once the file is confirmed to
 * exist.
 */
export function chromiumPath(): string | null {
  const explicit = process.env.CHROMIUM_PATH ?? process.env.PLAYWRIGHT_CHROMIUM_PATH;
  if (explicit) return explicit;

  try {
    const resolved = chromium.executablePath();
    return resolved && existsSync(resolved) ? resolved : null;
  } catch {
    return null;
  }
}

export function browserAvailable(): boolean {
  return chromiumPath() !== null;
}

/**
 * Skipping is right on a laptop and wrong in CI.
 *
 * A suite that quietly reports 94 skipped is indistinguishable, on the summary
 * page, from one that passed — so the moment this runs somewhere that is
 * supposed to have a browser, a missing browser has to be a failure. Locally it
 * stays a skip: a red X on a machine that was never going to have Chromium
 * teaches nothing.
 */
export function browserRequired(): boolean {
  return Boolean(process.env.CI);
}

async function freePort(): Promise<number> {
  const server = net.createServer();
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const { port } = server.address() as net.AddressInfo;
  await new Promise<void>((resolve) => server.close(() => resolve()));
  return port;
}

/**
 * The dev server a developer already has running.
 *
 * Next refuses to start a second dev server against the same directory, which
 * would make this suite fail for the person most likely to run it. It writes
 * where the first one is listening, so the right move is to use it rather than
 * to compete with it — the route reads the shop from disk on every request, so
 * a server started before these fixtures existed still serves them.
 */
async function runningDevServer(): Promise<string | null> {
  let lock: { appUrl?: unknown };
  try {
    lock = JSON.parse(await readFile(path.join(process.cwd(), ".next", "dev", "lock"), "utf8")) as { appUrl?: unknown };
  } catch {
    return null;
  }

  const appUrl = typeof lock.appUrl === "string" ? lock.appUrl.replace(/\/$/, "") : null;
  if (!appUrl) return null;

  // A lock file outlives the process that wrote it, so it is a hint rather
  // than an answer until something replies.
  try {
    const response = await fetch(appUrl, { signal: AbortSignal.timeout(3_000) });
    return response.ok || response.status === 404 ? appUrl : null;
  } catch {
    return null;
  }
}

async function waitForServer(url: string, timeoutMs: number): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  let lastError = "no attempt made";

  while (Date.now() < deadline) {
    try {
      const response = await fetch(url);
      if (response.ok) return;
      lastError = `HTTP ${response.status}`;
    } catch (error: unknown) {
      lastError = error instanceof Error ? error.message : String(error);
    }
    await new Promise((resolve) => setTimeout(resolve, 250));
  }

  throw new Error(`${url} did not come up within ${timeoutMs}ms (last: ${lastError})`);
}

export interface Harness {
  base: string;
  browser: Browser;
  /** Every mood's config, so a test can assert against what it asked for. */
  configs: Record<Mood, ShopConfig>;
  close: () => Promise<void>;
}

/**
 * One shop, five themes.
 *
 * Everything except `theme.mood` is held constant on purpose: it makes a
 * difference between two moods attributable to the mood and nothing else,
 * which is what lets the ordering assertions mean something.
 */
export async function startHarness(): Promise<Harness> {
  const executablePath = chromiumPath();
  if (!executablePath) throw new Error("No Chromium. Set CHROMIUM_PATH.");

  let store: FixtureStore | null = null;
  let next: ChildProcess | null = null;
  let browser: Browser | null = null;

  const shutdown = async (): Promise<void> => {
    await browser?.close().catch(() => {});
    if (next && next.exitCode === null) {
      next.kill("SIGTERM");
      await new Promise((resolve) => setTimeout(resolve, 200));
      if (next.exitCode === null) next.kill("SIGKILL");
    }
    await store?.close().catch(() => {});
    await Promise.all(
      MOODS.map((mood) => rm(path.join(process.cwd(), ".cache", "shop", `${keyFor(mood)}.json`), { force: true })),
    );
  };

  try {
    store = await startFixtureStore();

    // `renderer: null` keeps the browser rung of the ingest ladder shut. The
    // fixture serves `/products.json`, so the rung would never fire anyway, and
    // leaving it enabled would spawn a second Chromium for nothing.
    const ingest = await ingestStore(store.url, { renderer: null, respectRobots: true });
    const { config } = await merchandise(
      ingest,
      "a clean bio shop for the people arriving from their social links",
      { provider: createMockProvider() },
    );

    const configs = {} as Record<Mood, ShopConfig>;
    for (const mood of MOODS) {
      const themed: ShopConfig = { ...config, theme: { ...config.theme, mood } };
      configs[mood] = themed;
      await saveShop(keyFor(mood), {
        config: themed,
        catalogue: ingest.catalogue,
        ingestedAt: ingest.store.ingestedAt,
      });
    }

    let bootLog = "";
    let base = process.env.VISUAL_BASE_URL?.replace(/\/$/, "") ?? (await runningDevServer());

    if (!base) {
      const port = await freePort();
      // vitest runs with NODE_ENV=test, which is not a mode `next dev` has.
      const child = spawn("pnpm", ["exec", "next", "dev", "-p", String(port)], {
        cwd: process.cwd(),
        stdio: ["ignore", "ignore", "pipe"] as const,
        env: { ...process.env, NODE_ENV: "development" },
      });
      next = child;

      // Kept so a boot failure reports what Next said rather than only that
      // nothing answered.
      child.stderr?.on("data", (chunk: Buffer) => {
        bootLog = `${bootLog}${chunk.toString()}`.slice(-2000);
      });

      /*
       * `localhost`, not `127.0.0.1`, and the difference is not cosmetic.
       *
       * Chromium on Linux reads `http_proxy`/`https_proxy` from the
       * environment. It always bypasses the *name* `localhost`; a literal
       * `127.0.0.1` is matched against `no_proxy`, and that matching is not
       * reliable when the list carries CIDR entries. Inside a sandbox that
       * sets a proxy — a coding agent, a corporate laptop — the browser sends
       * requests for this server's own chunks to the proxy, which answers
       * 403.
       *
       * The symptom is brutal to read: the HTML arrives, twenty script tags
       * are in the DOM, and React never runs, because the one chunk that
       * failed was its runtime. Every assertion about post-hydration
       * behaviour then measures server-rendered HTML and reports a product
       * bug. Confirmed by loading the same page off the same server two ways:
       * `127.0.0.1` never hydrates, `localhost` hydrates immediately.
       */
      base = `http://localhost:${port}`;
    }

    try {
      await waitForServer(urlFor(base, "clean"), 90_000);
    } catch (error: unknown) {
      const said = next ? `\n\nnext dev said:\n${bootLog || "(nothing)"}` : "";
      throw new Error(`${error instanceof Error ? error.message : String(error)}${said}`);
    }

    browser = await chromium.launch({ executablePath, args: ["--no-sandbox"] });
    return { base, browser, configs, close: shutdown };
  } catch (error: unknown) {
    await shutdown();
    throw error;
  }
}

/**
 * Open a page and wait until it has stopped moving.
 *
 * `document.fonts.ready` is the one that matters: the display face is a local
 * woff2 and text measured before it lands is measured in the fallback, which
 * is a different width and a different height.
 */
/**
 * Wait until React has actually attached, rather than for a number of
 * milliseconds.
 *
 * This is the fix for a suite that had been red in CI for days while passing
 * on every developer's machine, which is the worst shape a test can take: the
 * people who could fix it were the people who could not see it.
 *
 * The cause was a warm cache. `networkidle` means the network went quiet, not
 * that the page is interactive — and on a dev server that has already compiled
 * the route, hydration follows within a few milliseconds, so a fixed settle
 * time covered it. On a cold CI runner the first request for a route compiles
 * it and its client chunks, hydration lands seconds later, and any assertion
 * about behaviour that only exists after hydration measured a page that was
 * still server-rendered HTML. Reproduced locally by deleting `.next` and
 * killing the dev server: 8 failures, exactly the ones CI reported.
 *
 * The signal is React's own fiber key on a hydrated host node. It is
 * deliberately *not* anything the tests assert on — gating on `[data-broken]`
 * would make the broken-imagery tests wait for their own conclusion and pass
 * vacuously, which the note in `geometry.test.ts` already warns about. This
 * waits for the precondition and leaves every assertion free to fail.
 */
/** Has React attached to this document yet? */
function hydrated(page: Page, timeout: number): Promise<unknown> {
  return page.waitForFunction(
    () => {
      const root = document.querySelector(".shop") ?? document.body;
      return Object.keys(root).some((key) => key.startsWith("__reactFiber$"));
    },
    undefined,
    // Interval polling, not the default rAF: in headless Chromium only one
    // page is visible at a time, and a backgrounded page has rAF suspended, so
    // on a suite that opens pages concurrently the predicate would never run.
    { polling: 100, timeout },
  );
}

/**
 * Wait until React has actually attached, rather than for a number of
 * milliseconds — and reload once if a cold dev server dropped a chunk.
 *
 * This is the fix for a suite that had been red in CI for days while passing
 * on every developer's machine, which is the worst shape a test can take: the
 * people who could fix it were the people who could not see it.
 *
 * `networkidle` means the network went quiet, not that the page is
 * interactive. On a dev server that has already compiled the route, hydration
 * follows within milliseconds, so the old fixed 1.2s settle covered it by
 * luck. On a cold one it does not, and the assertions then measure
 * server-rendered HTML — which is why the broken-imagery tests were the ones
 * failing. They are the only ones asserting on behaviour that requires
 * hydration, so a page whose JavaScript had not run yet came back looking like
 * a product bug: no `[data-broken]` marks, a white headline on a pale plate.
 *
 * The reload is a bounded safety net for the other way this fails — a client
 * chunk that never arrives at all. React does not retry a failed chunk, so the
 * page sits as server-rendered HTML forever and no amount of waiting helps.
 * One reload fixes a transient miss and reports the rest.
 *
 * **The 403 that made this hard to see was the sandbox's proxy, not the dev
 * server** — see the note on the base URL in `startHarness`, which is the
 * actual fix for that. It is recorded here because the two symptoms are
 * identical from inside a test, and the wrong one was chased first: a page
 * with twenty script tags in the DOM and no React on it looks the same
 * whether the runtime chunk was blocked or merely late.
 *
 * The signal is React's own fiber key on a hydrated host node, deliberately
 * *not* anything the tests assert on: gating on `[data-broken]` would make the
 * broken-imagery tests wait for their own conclusion and pass vacuously, which
 * the note in `geometry.test.ts` already warns about. This waits for the
 * precondition and leaves every assertion free to fail.
 */
export async function waitForHydration(page: Page): Promise<void> {
  try {
    // Generous before reaching for the reload. A cold Turbopack compile on a
    // contended runner is slow but *works*, and reloading at 8s turned every
    // page on such a runner into two page loads — which is how one CI run
    // reached seventy minutes without failing. Waiting costs nothing when
    // hydration is already done, which is the normal case.
    await hydrated(page, 25_000);
    return;
  } catch {
    // Fall through to the one reload.
  }

  await page.reload({ waitUntil: "networkidle" });
  await page.evaluate(() => document.fonts.ready);

  await hydrated(page, 20_000).catch(async (error: unknown) => {
    // A bare "Timeout exceeded" says nothing about which of the causes it was,
    // and this wait cost an hour of guessing once already.
    const seen = await page
      .evaluate(() => ({
        url: location.pathname,
        shop: Boolean(document.querySelector(".shop")),
        scripts: document.querySelectorAll("script").length,
      }))
      .catch(() => null);
    const noise = (page as unknown as { __noise?: string[] }).__noise ?? [];
    throw new Error(
      `hydration never completed, even after a reload: ${JSON.stringify(seen)}\n` +
        `${noise.slice(0, 8).join("\n")}\n(${String(error).slice(0, 120)})`,
    );
  });
}

export async function open(harness: Harness, mood: Mood, viewport: Viewport): Promise<Page> {
  const page = await harness.browser.newPage({
    viewport: { width: viewport.width, height: viewport.height },
  });
  const noise: string[] = [];
  page.on("pageerror", (e) => noise.push(`pageerror: ${e.message}`));
  page.on("console", (m) => {
    if (m.type() === "error") noise.push(`console: ${m.text().slice(0, 200)}`);
  });
  page.on("requestfailed", (r) => noise.push(`failed: ${r.url().slice(-80)}`));
  (page as unknown as { __noise: string[] }).__noise = noise;
  await page.goto(urlFor(harness.base, mood), { waitUntil: "networkidle" });
  await page.evaluate(() => document.fonts.ready);
  await waitForHydration(page);
  return page;
}

export interface Box {
  x: number;
  y: number;
  width: number;
  height: number;
  bottom: number;
}

/** Rounded, because a sub-pixel difference is not a regression. */
export async function boxOf(page: Page, selector: string): Promise<Box | null> {
  return page.evaluate((sel) => {
    const el = document.querySelector(sel);
    if (!el) return null;
    const r = el.getBoundingClientRect();
    return {
      x: Math.round(r.x),
      y: Math.round(r.y),
      width: Math.round(r.width),
      height: Math.round(r.height),
      bottom: Math.round(r.bottom),
    };
  }, selector);
}
